version: '3.8'

services:
    
    
 

    postgres:        
        image: postgres:14.5
        ports:
        - 5432:5432
      
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: scooby
            POSTGRES_DB: training

       
      
    customer:        
        build: .
        #image: imagename:tag
        ports:
        - 8484:8484
     
  
